project:
  type: website
website:
  title: "Daniel"
  site-url: "https://daniel-ec.netlify.app/"
  description: "Daniel Sánchez Personal Website"
  favicon: icon.jpeg
  twitter-card: 
    creator: "@daniel_ec18"
    image: icon.jpeg
    card-style: summary
  open-graph: true
  page-footer:
    left:
      - icon: github
        href: https://github.com/dsanchezp18
      - icon: twitter
        href: https://twitter.com/daniel_ec18
      - icon: linkedin
        href: https://www.linkedin.com/in/dsanchezp18/
      - icon: envelope
        href: mailto:dsanchezp998@gmail.com
      - text: RPubs
        href: https://rpubs.com/dsanchezp998
    right: 
      - text: Proudly built with Quarto through RStudio.
  navbar:
    title: Daniel Sánchez Pazmiño
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - research.qmd
      - teaching.qmd
      - resources.qmd
      - media.qmd
      - portfolio.qmd
      - posts_home.qmd
format:
  html:
    theme: 
      - cyborg
      - custom.scss
    toc: true

editor: source

