project:
  type: website

website:
  title: "Daniel Sánchez"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: source

