project:
  type: website

website:
  title: "Daniel Sánchez"
  site-url: "https://daniel-ec.netlify.app/"
  description: "Daniel Sánchez Personal Website"
  twitter-card: 
    creator: "@dsanchezp1826"
    card-style: summary
  page-footer:
    left:
      - icon: github
        href: https://github.com/dsanchezp18
      - icon: twitter
        href: https://twitter.com/dsanchezp1826
      - icon: linkedin
        href: https://www.linkedin.com/in/dsanchezp18/
      - icon: envelope
        href: mailto:dsanchezp998@gmail.com
      - text: RPubs
        href: https://rpubs.com/dsanchezp998
    right: 
      - text: Proudly built with Quarto from RStudio.
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - teaching.qmd
      - resources.qmd
      - posts_home.qmd

format:
  html:
    theme: cyborg
    mainfont: "Lato"
    css: styles.css
    toc: true

editor: source

